// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeSsDhL4xO2iDoniXQZ5ch70Zv6Un38LU',
    appId: '1:366699841816:web:3b14f0a3579879e611766d',
    messagingSenderId: '366699841816',
    projectId: 'flutter-note-2feb3',
    authDomain: 'flutter-note-2feb3.firebaseapp.com',
    storageBucket: 'flutter-note-2feb3.firebasestorage.app',
    measurementId: 'G-HPZKQ6KY8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSiUPJG9Wc5gFF5Tl9fGF4td_rsiNhvk8',
    appId: '1:366699841816:android:c53d551d8c37ea2a11766d',
    messagingSenderId: '366699841816',
    projectId: 'flutter-note-2feb3',
    storageBucket: 'flutter-note-2feb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfafm1MO6qkJLK-32Gz6et7ueFTMXrgs',
    appId: '1:366699841816:ios:64de244c44cf7aef11766d',
    messagingSenderId: '366699841816',
    projectId: 'flutter-note-2feb3',
    storageBucket: 'flutter-note-2feb3.firebasestorage.app',
    iosBundleId: 'com.example.flutterNote',
  );
}
